title: Transit
baseurl: /
menu:
  actions:
    - label: Sign Up
      url: generic.md
      is_scrolly: false
      is_primary: true
    - label: Log In
      url: generic.md
      is_scrolly: false
      is_primary: false
footer:
  copyright: '&copy; Transit. Al rights reserved.'
  social_links:
    - title: Twitter
      icon: fa-twitter
      link_url: '#'
    - title: Facebook
      icon: fa-facebook
      link_url: '#'
    - title: Instagram
      icon: fa-instagram
      link_url: '#'
    - title: LinkedIn
      icon: fa-linkedin
      link_url: '#'
    - title: GitHub
      icon: fa-github
      link_url: '#'
palette: cyan
palettes:
  cyan:
    sass:
      bg_overlay: '#476777'
      highlight: '#54c3e1'
      accent1: '#54c3e1'
      accent2: '#6bc378'
      accent3: '#5da49b'
      accent4: '#6e7baa'
  magenta:
    sass:
      bg_overlay: '#4c4777'
      highlight: '#ee6588'
      accent1: '#ee6588'
      accent2: '#f69560'
      accent3: '#937f8f'
      accent4: '#5a6284'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
permalink: '/posts/:slug:output_ext'
