---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: document
  path: _config.yml
  label: Config
  templates:
  - config
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: document
  path: elements.md
  label: Elements
  templates:
  - elements
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
